### PR TITLE
Fix deadlock on RWLock

### LINKED ISSUE #80: Deadlock in RWLock.write()
**Describe the bug**
A deadlock is found when broadcasting a message and, in the meanwhile, another message is decoded from the network.
This happens only when `broadcast` and `listen` are executed concurrently

### PR DESCRIPTION
**Pull request by herr-seppia**
- Drop the RWLockGuard as soon as possible
- Improve logs
- Bump version to 0.3.0-rc.0

Resolves #80

### CODE REVIEW

File: src/transport.rs [hunk 1]
```diff
@@ -68,7 +68,11 @@ impl WireNetwork {
         info!("Listening on: {}", socket.local_addr()?);
         loop {
             let mut bytes = [0; MAX_DATAGRAM_SIZE];
-            let (_, remote_address) = socket.recv_from(&mut bytes).await?;
+            let (_, remote_address) =
+                socket.recv_from(&mut bytes).await.map_err(|e| {
```
Comment (autholykos) [inline src/transport.rs:72]: This error does not seem to be handled. The function always returns an IP address

File: src/mantainer.rs [hunk 2]
```diff
@@ -48,7 +48,7 @@ impl TableMantainer {
         outbound_sender: Sender<MessageBeanOut>,
     ) {
         debug!("TableMantainer::monitor_buckets started");
-        let idle_time: Duration = ktable.read().await.config.bucket_ttl;
+        let idle_time: Duration = { ktable.read().await.config.bucket_ttl };
         loop {
```
Comment (autholykos) [inline src/mantainer.rs:52]: If the reason to add an additional scope is to drop the lock, there should be a comment for it. Actually there should be a comment anyway, since the code is not clear

**Review by autholykos — APPROVED** [review]
Generally, it looks good but there are a couple of optional nits you might wanna address. Nothing blocking though
